name = "ColorDrop"
license = "MIT"
licenselink = "https://github.com/humrochagf/colordrop/blob/master/LICENSE.md"
description = "Customizable, monochromatic and minimalist hugo theme for personal blogs"
homepage = "https://humberto.io/"
tags = ["blog", "customizable", "monochromatic", "mimimalist"]
features = ["blog", "tags", "curriculum"]
min_version = 0.55

[author]
  name = "Humberto Rocha"
  homepage = "https://humberto.io"
